version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  mongodb_data: 