version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongodb

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 